services:
  # Relational database for games, words, and embeddings
  db:
    image: ankane/pgvector:latest
    container_name: codenames-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # NoSQL database for raw JSON from LLMs
  mongodb:
    image: mongo:latest
    container_name: codenames-mongo
    restart: always # Always restart if it fails
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Local LLM inference via Ollama
  ollama:
    image: ollama/ollama:latest
    container_name: codenames-ollama
    entrypoint: [ "/bin/bash", "/ollama_entrypoint.sh" ]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Persists downloaded models and configurations across restarts
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh:ro
      - ./backend/app/config/llm_models.py:/llm_models.py:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  # Backend with FastAPI
  app:
    build: ./backend
    container_name: codenames-backend
    working_dir: /workspace
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/workspace # Backend source code
      - ./data:/workspace/data # External files for words and biases
    ports:
      - "8000:8000"
    env_file:
      - .env # Include environment variables from .env file
    depends_on:
      - db
      - mongodb
      - ollama

volumes:
  postgres_data:
  mongo_data:
  ollama_data:
