from pydantic import BaseModel, model_validator, Field
from typing import Optional, Literal, Any


class LLMMessage(BaseModel):
    """
    A message in the conversation between the LLM and the human player. It has a role (system, user,
    or assistant) and content (the text of the message). 

    This model is used to structure the messages that are sent to and received from the LLM, 
    ensuring that they adhere to the expected format and contain valid data.)
    """
    role: Literal["system", "user", "assistant"]
    content: str  # The content of the message

    @model_validator(mode="after")
    def model_validation(self) -> "LLMMessage":
        """
        Validates the content of the message to ensure it is not empty or just whitespace.

        :return: The validated LLMMessage instance.
        """
        if not self.content.strip():
            raise ValueError("Content of the message cannot be empty.")

        return self


class TokenUsage(BaseModel):
    """
    A model to track the token usage for interactions with the LLM. It includes the number of tokens
    in the prompt sent to the LLM, the number of tokens in the response generated by the LLM, and
    the total number of tokens used (prompt + completion). 

    This model is useful for monitoring token usage and ensuring that it stays within any limits set
    by the LLM provider.
    """
    # Number of tokens in the prompt sent to the LLM
    prompt_tokens: int = Field(ge=0)
    # Number of tokens in the response generated by the LLM
    completion_tokens: int = Field(ge=0)
    # Total number of tokens used (prompt + completion)
    total_tokens: Optional[int] = None

    @model_validator(mode="after")
    def calculate_total_tokens(self) -> "TokenUsage":
        """
        Calculates the total number of tokens used based on the prompt and completion tokens.

        :return: The validated TokenUsage instance with total_tokens calculated.
        """
        if self.total_tokens is None:
            self.total_tokens = self.prompt_tokens + self.completion_tokens
        elif self.total_tokens != self.prompt_tokens + self.completion_tokens:
            raise ValueError(
                "Total tokens must be equal to the sum of prompt tokens and completion tokens.")

        return self


class LLMRequest(BaseModel):
    """
    A request to the LLM, containing a list of messages in the conversation, the model being used,
    temperature and max tokens settings for the response, a timeout for the response, optional
    metadata for logging purposes, and the expected response format ("json" or "text").

    This model ensures that all necessary information is included in the request and that it adheres
    to the expected format, allowing for proper validation and handling of the request when it is
    sent to the LLM.
    """
    # List of messages in the conversation
    messages: list[LLMMessage]
    # The LLM model being used for the request
    model: str
    # Temperature setting for the LLM response (default is 0.7)
    temperature: float = Field(ge=0.0, le=2.0, default=0.7)
    # Maximum number of tokens for the LLM response (default is 120, must be non-negative)
    max_tokens: int = Field(ge=1, default=120)
    # Timeout for the LLM response in seconds (default is 30, must be non-negative)
    timeout_s: int = Field(ge=1, default=30)
    # Additional metadata for logging purposes
    metadata: dict[str, Any] = Field(default_factory=dict)
    # Response format for the LLM output (default is "json", must be either "json" or "text")
    response_format: Literal["json", "text"] = "json"

    @model_validator(mode="after")
    def validate_request(self) -> "LLMRequest":
        # Validate that there is at least one message in the request
        if not self.messages:
            raise ValueError(
                "At least one message must be provided in the request.")

        # At least one message must have the role of "user" to ensure that there is a user input for
        # the LLM to respond to.
        if not any(message.role == "user" for message in self.messages):
            raise ValueError(
                "At least one message must have the role of 'user'.")

        # Validate that the model name is not empty or just whitespace
        if not self.model.strip():
            raise ValueError("Model name cannot be empty.")

        return self


class LLMResponse(BaseModel):
    """
    A response from the LLM, containing the text of the response, the model that generated it, the
    latency of the response, optional token usage information, an optional finish reason for the 
    response, the raw payload returned by the LLM provider, an optional request ID for tracking, the 
    execution mode of the response, and the LLM provider.

    This model ensures that the response from the LLM is structured in a consistent way and that it
    contains all necessary information for processing the response and handling any errors that may
    arise from the interaction with the LLM.
    """
    # The text of the response generated by the LLM
    text: str
    # The LLM model that generated the response
    model_used: str
    # The latency of the response in milliseconds (must be non-negative)
    latency_ms: int = Field(ge=0)
    # Optional token usage information for the request and response
    usage: Optional[TokenUsage] = None
    # Optional finish reason for the response (e.g., "stop", "length", "timeout", etc.)
    finish_reason: Optional[str] = None
    # The raw payload returned by the LLM provider, which may include additional information about
    # the response that is not captured in the other fields. This is stored as a dictionary to allow
    # for flexibility in the structure of the data returned by different LLM providers.
    raw_payload: dict[str, Any] = Field(default_factory=dict)
    # Optional request ID for tracking the request that generated this response
    request_id: Optional[str] = None
    # The execution mode of the LLM response
    execution_mode: Literal["api", "local"] = "local"
    # The LLM provider (e.g., "openai", "azure", etc.)
    provider: Optional[str] = None

    @model_validator(mode="after")
    def validate_response(self) -> "LLMResponse":
        # Validate that the response text is not empty or just whitespace
        if not self.text.strip():
            raise ValueError("Response text cannot be empty.")

        # Validate that the model used is not empty or just whitespace
        if not self.model_used.strip():
            raise ValueError("Model used cannot be empty.")

        return self


class ClueProposal(BaseModel):
    """
    A proposal for a clue in the game, containing the text of the clue, the count of how many words
    are associated with the clue, and the raw payload returned by the LLM provider for the proposal.
    """
    # The text of the clue proposed by the LLM
    clue: str
    # The count of how many words are associated with the clue. This must be a positive integer.
    count: int = Field(ge=1)
    # The raw payload returned by the LLM provider for the proposal
    raw_payload: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_clue_proposal(self) -> "ClueProposal":
        # Validate that the clue text is not empty or just whitespace
        if not self.clue.strip():
            raise ValueError("Clue cannot be empty.")

        return self


class GuessProposal(BaseModel):
    """
    A proposal for a guess in the game, containing the card word proposed by the LLM and the raw
    payload returned by the LLM provider for the proposal. The card word must be a non-empty string,
    and the raw payload is stored as a dictionary.
    """
    # The card word proposed by the LLM for the guess
    card_word: str
    # The raw payload returned by the LLM provider for the proposal
    raw_payload: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_guess_proposal(self) -> "GuessProposal":
        # Validate that the card word is not empty or just whitespace
        if not self.card_word.strip():
            raise ValueError("Card word cannot be empty.")

        return self
