from pydantic import BaseModel, model_validator, Field
from typing import Optional, Literal


class LLMMessage(BaseModel):
    """
    A message in the conversation between the LLM and the human player. It has a role (system, user,
    or assistant) and content (the text of the message). This model is used to structure the 
    messages that are sent to and received from the LLM, ensuring that they adhere to the expected
    format and contain valid data.)
    """
    role: Literal["system", "user", "assistant"]
    content: str  # The content of the message

    @model_validator(mode="before")
    def model_validation(self) -> "LLMMessage":
        """
        Validates the content of the message to ensure it is not empty or just whitespace.

        :return: The validated LLMMessage instance.
        """
        if not self.content.strip():
            raise ValueError("Content of the message cannot be empty.")

        return self


class TokenUsage(BaseModel):
    """
    A model to track the token usage for interactions with the LLM. It includes the number of tokens
    in the prompt sent to the LLM, the number of tokens in the response generated by the LLM, and
    the total number of tokens used (prompt + completion). This model is useful for monitoring
    token usage and ensuring that it stays within any limits set by the LLM provider.
    """
    # Number of tokens in the prompt sent to the LLM
    prompt_tokens: int = Field(ge=0)
    # Number of tokens in the response generated by the LLM
    completion_tokens: int = Field(ge=0)
    # Total number of tokens used (prompt + completion)
    total_tokens: Optional[int] = None

    @model_validator(mode="after")
    def calculate_total_tokens(self) -> "TokenUsage":
        """
        Calculates the total number of tokens used based on the prompt and completion tokens.

        :return: The validated TokenUsage instance with total_tokens calculated.
        """
        if self.total_tokens is None:
            self.total_tokens = self.prompt_tokens + self.completion_tokens
        elif self.total_tokens != self.prompt_tokens + self.completion_tokens:
            raise ValueError(
                "Total tokens must be equal to the sum of prompt tokens and completion tokens.")

        return self
